#!/bin/sh
#
# run
#
# David Adams
# November 2015
# Generate a sample

HELP=
CLEAN=
DBG=
while getopts hcd: OPT; do
  case $OPT in
  h) HELP=true;;
  c) CLEAN=true;;
  d) DBG=$OPTARG;;
  esac
done
shift $(( OPTIND-1 ))
SAMPLE=$1

if [ -n "$CLEAN" ]; then
  rm -f ${SAMPLE}_hist.root ${SAMPLE}_event.root ${SAMPLE}.log
  rm -f ${SAMPLE}perf.root ${SAMPLE}perf.log
fi

if [ ! -r ${SAMPLE}.fcl ]; then
  echo Unable to find input file ${SAMPLE}.fcl
  exit 1
fi

# Generate event data.
if [ ! -r ${SAMPLE}_event.root ]; then
  rm -f ${SAMPLE}perf.root
  echo
  echo run: Generating event data.
  echo " Start: "`date`
  COM="lar -n 5 -c ${SAMPLE}.fcl -T ${SAMPLE}_hist.root -o ${SAMPLE}_event.root"
  echo $COM >${SAMPLE}.log
  $COM 2>&1 >> ${SAMPLE}.log
  STAT=$?
  echo Finish: `date`
  if [ $STAT -ne 0 -o ! -r ${SAMPLE}_event.root ]; then
    echo run: Event generation failed.
    exit 1
  fi
  fcldump ${SAMPLE}.fcl 10 > ${SAMPLE}.fcldump
fi

# Generate histograms.
if [ ! -r ${SAMPLE}perf.root ]; then
  echo
  echo run: Generating histograms.
  echo " Start: "`date`
  if echo $SAMPLE | grep old 1>/dev/null; then
    FCL=perf35told.fcl
  else
    FCL=perf35t.fcl
  fi
  COM="lar -c $FCL -s ${SAMPLE}_event.root -T ${SAMPLE}perf.root"
  echo $COM
  $COM 2>&1 >${SAMPLE}perf.log
  STAT=$?
  echo Finish: `date`
  if [ $STAT -ne 0 -o ! -r ${SAMPLE}perf.root ]; then
    echo run: Histogram generation failed.
    exit 1
  fi
fi
