#!/bin/bash

# David Adams
# November 2015
#
# Script to test the raw data simulation module SimWireDune.

HELP=
CLEAN=
DBG=0
SAMTEST=mu35tnew
SAMREF=mu35tnewref
while getopts hct:r:d: OPT; do
  case $OPT in
  h) HELP=true;;
  c) CLEAN=true;;
  t) SAMTEST=$OPTARG;;
  r) SAMREFS=$OPTARG;;
  d) DBG=$OPTARG;;
  esac
done
shift $(( OPTIND-1 ))

# If the test sample is not given, then use mu35tnew.
if [ -z "$SAMTEST" ]; then
  SAM1=mu35tnew
fi
if [ -z "$SAM2" ]; then
  SAM2=mu35tnewref
fi

# Generate test sample.
ARG=
if [ -n "$CLEAN" ]; then
  ARG="-c"
fi
echo
echo Generating test sample.
if ! ./run $ARG $SAMTEST; then
  echo Sample generation failed
  exit 1 
fi

if [ -n "$HELP" ]; then
  echo "Usage: $0 [-h] [-c] [-d VAL] [-t TEST_SAMPLE] [-r REF_SAMPLE]"
  echo   "-h: This message"
  echo   "-d: Run comparison at debug level VAL"
  echo   "    VAL = 1 shows differing channels"
  echo   "-t: Arg is name for test sample [mu35tnew]"
  echo   "-r: Arg is name for reference sample [mu35tnewref]"
  echo   "-c: Regenerate test sample."
  exit 0
fi

# Compare histograms.
echo
echo Comparing histograms.
dxroot compareHists.C'("'$SAM1'","'$SAM2'",'$DBG')' 2>&1 | tee compare.log
STAT=$?
if [ $STAT -ne 0 ]; then
  Histogram comparison failed.
  exit 1
fi

echo
echo Done
